ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'SUBMIT';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'START_REVIEW';

DELETE FROM audit_logs
WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '7 days';
