package com.digitalarchive.service;

import com.digitalarchive.domain.entity.Category;
import com.digitalarchive.domain.entity.Department;
import com.digitalarchive.domain.entity.Document;
import com.digitalarchive.domain.entity.DocumentWorkflowHistory;
import com.digitalarchive.domain.entity.AppUser;
import com.digitalarchive.domain.enums.AuditAction;
import com.digitalarchive.domain.enums.ClassificationLevel;
import com.digitalarchive.domain.enums.DocumentStatus;
import com.digitalarchive.domain.enums.ResourceType;
import com.digitalarchive.dto.CreateDocumentRequest;
import com.digitalarchive.dto.DocumentResponse;
import com.digitalarchive.dto.UpdateDocumentRequest;
import com.digitalarchive.exception.ResourceNotFoundException;
import com.digitalarchive.mapper.ApiResponseMapper;
import com.digitalarchive.repository.CategoryRepository;
import com.digitalarchive.repository.DepartmentRepository;
import com.digitalarchive.repository.DocumentRepository;
import com.digitalarchive.repository.DocumentWorkflowHistoryRepository;
import com.digitalarchive.repository.AppUserRepository;
import jakarta.persistence.EntityManager;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.security.oauth2.jwt.Jwt;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * All business rules for documents live here, not in the controller.
 * The controller's job is just HTTP in/out; this class owns the "how".
 */
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class DocumentService {

    private final DocumentRepository documentRepository;
    private final DocumentWorkflowHistoryRepository workflowHistoryRepository;
    private final AppUserRepository appUserRepository;
    private final CategoryRepository categoryRepository;
    private final DepartmentRepository departmentRepository;
    private final AuditService auditService;
    private final EntityManager entityManager;
    private final ApiResponseMapper responseMapper;
    private final DocumentAccessService documentAccessService;

    /**
     * Every new document starts as DRAFT and defaults to INTERNAL classification
     * if the caller doesn't specify one.
     *
     * reference_number is NOT set here — it's auto-generated by a Postgres
     * trigger (V6__create_triggers.sql) the moment the row is inserted. That's
     * why Document.referenceNumber is mapped insertable=false, updatable=false.
     */
    @Transactional
    public DocumentResponse createDocument(
            CreateDocumentRequest request,
            UUID createdByUserSub,
            boolean administrator,
            Jwt jwt) {
        DocumentAccessService.AccessContext access = documentAccessService.context(jwt);
        if (request.getClassification() != null && !access.has(com.digitalarchive.domain.enums.ApplicationRole.ARCHIVIST)) {
            throw new org.springframework.security.access.AccessDeniedException(
                    "Only an archive officer may set document classification");
        }
        Category category = categoryRepository.findById(request.getCategoryId())
                .filter(existing -> existing.getDeletedAt() == null)
                .orElseThrow(() -> new ResourceNotFoundException("Category not found: " + request.getCategoryId()));

        boolean hasOtherDepartment = request.getOtherDepartmentName() != null
                && !request.getOtherDepartmentName().isBlank();
        if (request.getDepartmentId() == null && !hasOtherDepartment) {
            throw new IllegalArgumentException("Choose a department or provide an other department name");
        }
        if (request.getDepartmentId() != null && hasOtherDepartment) {
            throw new IllegalArgumentException("Choose either a listed department or an other department name");
        }
        if (access.has(com.digitalarchive.domain.enums.ApplicationRole.DEPT_USER)
                && !access.hasAny(com.digitalarchive.domain.enums.ApplicationRole.ADMIN,
                        com.digitalarchive.domain.enums.ApplicationRole.ARCHIVIST)
                && (request.getDepartmentId() == null || !request.getDepartmentId().equals(access.departmentId()))) {
            throw new org.springframework.security.access.AccessDeniedException(
                    "Department users may only submit documents to their own department");
        }

        Department department = request.getDepartmentId() == null ? null
                : departmentRepository.findById(request.getDepartmentId())
                        .filter(existing -> existing.getDeletedAt() == null)
                        .orElseThrow(() -> new ResourceNotFoundException("Department not found: " + request.getDepartmentId()));

        DocumentStatus initialStatus = administrator
                ? DocumentStatus.ARCHIVED
                : DocumentStatus.SUBMITTED;
        AppUser uploader = appUserRepository.findById(createdByUserSub)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "Uploader profile not found: " + createdByUserSub));

        Document document = Document.builder()
                .title(request.getTitle())
                .description(request.getDescription())
                .category(category)
                .department(department)
                .otherDepartmentName(hasOtherDepartment ? request.getOtherDepartmentName().trim() : null)
                .classification(request.getClassification() != null
                        ? request.getClassification()
                        : ClassificationLevel.INTERNAL)
                .status(initialStatus)
                .archivedAt(administrator ? OffsetDateTime.now() : null)
                .createdBy(createdByUserSub)
                .uploaderUsername(uploader.getUsername())
                .uploaderFullName(uploader.getFullName())
                .uploaderEmail(uploader.getEmail())
                .uploaderDepartmentId(
                        uploader.getDepartment() == null
                                ? null
                                : uploader.getDepartment().getDepartmentId())
                .uploaderDepartmentName(
                        uploader.getDepartment() == null
                                ? null
                                : uploader.getDepartment().getName())
                .build();

        Document saved = documentRepository.saveAndFlush(document);

        // The trigger sets reference_number on INSERT, so refresh the managed
        // entity after flushing to load the generated value.
        entityManager.refresh(saved);

        workflowHistoryRepository.save(DocumentWorkflowHistory.builder()
                .document(saved)
                .fromStatus(null)
                .toStatus(initialStatus)
                .comment(administrator
                        ? "Automatically archived because the creator is an administrator"
                        : "Automatically submitted for review")
                .changedBy(createdByUserSub)
                .build());

        auditService.log(createdByUserSub, AuditAction.CREATE, ResourceType.DOCUMENT,
                saved.getDocumentId(), "Created document: " + saved.getTitle()
                        + " with status " + initialStatus);

        return responseMapper.toDocumentResponse(saved);
    }

    public List<DocumentResponse> listActiveDocuments(Jwt jwt) {
        DocumentAccessService.AccessContext access = documentAccessService.context(jwt);
        return documentRepository.findAll().stream()
                .filter(d -> d.getDeletedAt() == null)
                .filter(d -> documentAccessService.canRead(d, access))
                .map(responseMapper::toDocumentResponse)
                .toList();
    }

    public List<DocumentResponse> listReviewQueue(Jwt jwt) {
        DocumentAccessService.AccessContext access = documentAccessService.context(jwt);
        if (access.has(com.digitalarchive.domain.enums.ApplicationRole.MANAGER)
                && access.departmentId() == null) {
            return List.of();
        }
        return documentRepository
                .findByStatusInAndDeletedAtIsNullOrderByCreatedAtDesc(
                        List.of(
                                DocumentStatus.SUBMITTED,
                                DocumentStatus.UNDER_REVIEW,
                                DocumentStatus.APPROVED))
                .stream()
                .filter(d -> !access.has(com.digitalarchive.domain.enums.ApplicationRole.MANAGER)
                        || (d.getDepartment() != null
                                && d.getDepartment().getDepartmentId().equals(access.departmentId())))
                .filter(d -> documentAccessService.canRead(d, access))
                .map(responseMapper::toDocumentResponse)
                .toList();
    }

    public Optional<DocumentResponse> getActiveById(UUID id, Jwt jwt) {
        DocumentAccessService.AccessContext access = documentAccessService.context(jwt);
        return findActiveEntity(id).map(document -> {
            documentAccessService.requireRead(document, access);
            return responseMapper.toDocumentResponse(document);
        });
    }

    /**
     * Backs the full-text search endpoint. Delegates straight to the
     * tsvector-based native query already defined on DocumentRepository.
     */
    public List<DocumentResponse> searchDocuments(String searchTerm, Jwt jwt) {
        DocumentAccessService.AccessContext access = documentAccessService.context(jwt);
        return documentRepository.searchByTitleOrDescription(searchTerm).stream()
                .filter(d -> d.getDeletedAt() == null)
                .filter(d -> documentAccessService.canRead(d, access))
                .map(responseMapper::toDocumentResponse)
                .toList();
    }

    @Transactional
    public Optional<DocumentResponse> updateDocument(
            UUID id,
            UpdateDocumentRequest request,
            UUID updatedByUserSub,
            Jwt jwt) {
        DocumentAccessService.AccessContext access = documentAccessService.context(jwt);
        return findActiveEntity(id).map(existing -> {
            documentAccessService.requireWrite(existing, access);
            if (request.getClassification() != null && !access.has(com.digitalarchive.domain.enums.ApplicationRole.ARCHIVIST)) {
                throw new org.springframework.security.access.AccessDeniedException(
                        "Only an archive officer may change document classification");
            }
            if (request.getTitle() != null) {
                existing.setTitle(request.getTitle());
            }
            if (request.getDescription() != null) {
                existing.setDescription(request.getDescription());
            }
            if (request.getClassification() != null) {
                existing.setClassification(request.getClassification());
            }
            if (request.getCategoryId() != null) {
                Category category = categoryRepository.findById(request.getCategoryId())
                        .filter(candidate -> candidate.getDeletedAt() == null)
                        .orElseThrow(
                                () -> new ResourceNotFoundException("Category not found: " + request.getCategoryId()));
                existing.setCategory(category);
            }
            existing.setUpdatedBy(updatedByUserSub);
            Document saved = documentRepository.save(existing);

            auditService.log(updatedByUserSub, AuditAction.UPDATE, ResourceType.DOCUMENT,
                    saved.getDocumentId(), "Updated document: " + saved.getTitle());

            return responseMapper.toDocumentResponse(saved);
        });
    }

    /**
     * Soft delete — matches the deleted_at/deleted_by pattern already in the
     * schema.
     * Rows are never physically removed; deleted_at != null means "hidden from
     * normal views".
     */
    @Transactional
    public boolean softDelete(UUID id, UUID deletedByUserSub) {
        return findActiveEntity(id).map(existing -> {
            existing.setDeletedAt(OffsetDateTime.now());
            existing.setDeletedBy(deletedByUserSub);
            documentRepository.save(existing);

            auditService.log(deletedByUserSub, AuditAction.DELETE, ResourceType.DOCUMENT,
                    existing.getDocumentId(), "Soft-deleted document: " + existing.getTitle());

            return true;
        }).orElse(false);
    }

    private Optional<Document> findActiveEntity(UUID id) {
        return documentRepository.findById(id)
                .filter(document -> document.getDeletedAt() == null);
    }
}
