package com.digitalarchive.service;

import com.digitalarchive.domain.entity.Category;
import com.digitalarchive.domain.entity.Department;
import com.digitalarchive.domain.entity.Document;
import com.digitalarchive.domain.enums.AuditAction;
import com.digitalarchive.domain.enums.ClassificationLevel;
import com.digitalarchive.domain.enums.DocumentStatus;
import com.digitalarchive.domain.enums.ResourceType;
import com.digitalarchive.dto.CreateDocumentRequest;
import com.digitalarchive.dto.UpdateDocumentRequest;
import com.digitalarchive.repository.CategoryRepository;
import com.digitalarchive.repository.DepartmentRepository;
import com.digitalarchive.repository.DocumentRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * All business rules for documents live here, not in the controller.
 * The controller's job is just HTTP in/out; this class owns the "how".
 */
@Service
@RequiredArgsConstructor
public class DocumentService {

    private final DocumentRepository documentRepository;
    private final CategoryRepository categoryRepository;
    private final DepartmentRepository departmentRepository;
    private final AuditService auditService;

    /**
     * Every new document starts as DRAFT and defaults to INTERNAL classification
     * if the caller doesn't specify one.
     *
     * reference_number is NOT set here — it's auto-generated by a Postgres
     * trigger (V6__create_triggers.sql) the moment the row is inserted. That's
     * why Document.referenceNumber is mapped insertable=false, updatable=false.
     */
    public Document createDocument(CreateDocumentRequest request, UUID createdByUserSub) {
        Category category = categoryRepository.findById(request.getCategoryId())
                .orElseThrow(() -> new IllegalArgumentException("Category not found: " + request.getCategoryId()));

        Department department = departmentRepository.findById(request.getDepartmentId())
                .orElseThrow(() -> new IllegalArgumentException("Department not found: " + request.getDepartmentId()));

        Document document = Document.builder()
                .title(request.getTitle())
                .description(request.getDescription())
                .category(category)
                .department(department)
                .classification(request.getClassification() != null
                        ? request.getClassification()
                        : ClassificationLevel.INTERNAL)
                .status(DocumentStatus.DRAFT)
                .createdBy(createdByUserSub)
                .build();

        Document saved = documentRepository.save(document);

        // The trigger sets reference_number on INSERT, but the entity we just
        // built in memory doesn't know that yet — re-fetch to get the real value.
        Document reloaded = documentRepository.findById(saved.getDocumentId()).orElseThrow();

        auditService.log(createdByUserSub, AuditAction.CREATE, ResourceType.DOCUMENT,
                reloaded.getDocumentId(), "Created document: " + reloaded.getTitle());

        return reloaded;
    }

    public List<Document> listActiveDocuments() {
        return documentRepository.findAll().stream()
                .filter(d -> d.getDeletedAt() == null)
                .toList();
    }

    public Optional<Document> getActiveById(UUID id) {
        return documentRepository.findById(id)
                .filter(d -> d.getDeletedAt() == null);
    }

    /**
     * Backs the full-text search endpoint. Delegates straight to the
     * tsvector-based native query already defined on DocumentRepository.
     */
    public List<Document> searchDocuments(String searchTerm) {
        return documentRepository.searchByTitleOrDescription(searchTerm).stream()
                .filter(d -> d.getDeletedAt() == null)
                .toList();
    }

    public Optional<Document> updateDocument(UUID id, UpdateDocumentRequest request, UUID updatedByUserSub) {
        return getActiveById(id).map(existing -> {
            if (request.getTitle() != null) {
                existing.setTitle(request.getTitle());
            }
            if (request.getDescription() != null) {
                existing.setDescription(request.getDescription());
            }
            if (request.getClassification() != null) {
                existing.setClassification(request.getClassification());
            }
            if (request.getCategoryId() != null) {
                Category category = categoryRepository.findById(request.getCategoryId())
                        .orElseThrow(
                                () -> new IllegalArgumentException("Category not found: " + request.getCategoryId()));
                existing.setCategory(category);
            }
            existing.setUpdatedBy(updatedByUserSub);
            Document saved = documentRepository.save(existing);

            auditService.log(updatedByUserSub, AuditAction.UPDATE, ResourceType.DOCUMENT,
                    saved.getDocumentId(), "Updated document: " + saved.getTitle());

            return saved;
        });
    }

    /**
     * Soft delete — matches the deleted_at/deleted_by pattern already in the
     * schema.
     * Rows are never physically removed; deleted_at != null means "hidden from
     * normal views".
     */
    public boolean softDelete(UUID id, UUID deletedByUserSub) {
        return getActiveById(id).map(existing -> {
            existing.setDeletedAt(OffsetDateTime.now());
            existing.setDeletedBy(deletedByUserSub);
            documentRepository.save(existing);

            auditService.log(deletedByUserSub, AuditAction.DELETE, ResourceType.DOCUMENT,
                    existing.getDocumentId(), "Soft-deleted document: " + existing.getTitle());

            return true;
        }).orElse(false);
    }
}